version: '3'

services:
  tracktor:
    build:
      dockerfile: ./Dockerfile
      context: ""
    container_name: tracktor
    depends_on:
      - database
    networks:
      - backend
    ports:
      - 80:80
    environment:
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/opt/tracktor/data/tracktor.db

#      FOR POSTGRES
#      - DATABASE_TYPE=postgresql
#      - DATABASE_USER=tracktor
#      - DATABASE_PASS=tracktor
#      - DATABASE_HOST=database
#      - DATABASE_NAME=tracktor
    volumes:
      - ./data:/opt/tracktor/data

#  database:
#    image: postgres:14.0-alpine
#    environment:
#      - POSTGRES_USER=tracktor
#      - POSTGRES_PASSWORD=tracktor
#      - POSTGRES_DB=tracktor
#    networks:
#      - backend

networks:
  backend: