"""add playlist, image and item models entities

Revision ID: 6a9fa8ce4021
Revises: a2ced875a244
Create Date: 2022-02-20 15:20:43.105844

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6a9fa8ce4021'
down_revision = 'a2ced875a244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist',
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spotify', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amazon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apple_music', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlistitemlink',
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'item_id')
    )
    op.drop_index('ix_category_id', table_name='category')
    op.drop_index('ix_category_name', table_name='category')
    op.drop_index('ix_category_playlists', table_name='category')
    op.drop_column('category', 'playlists')
    op.drop_index('ix_user_admin', table_name='user')
    op.drop_index('ix_user_created_at', table_name='user')
    op.drop_index('ix_user_entity_id', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_last_login', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('ix_user_password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_password', 'user', ['password'], unique=False)
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_last_login', 'user', ['last_login'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_entity_id', 'user', ['entity_id'], unique=False)
    op.create_index('ix_user_created_at', 'user', ['created_at'], unique=False)
    op.create_index('ix_user_admin', 'user', ['admin'], unique=False)
    op.add_column('category', sa.Column('playlists', sa.VARCHAR(), nullable=False))
    op.create_index('ix_category_playlists', 'category', ['playlists'], unique=False)
    op.create_index('ix_category_name', 'category', ['name'], unique=False)
    op.create_index('ix_category_id', 'category', ['id'], unique=False)
    op.drop_table('playlistitemlink')
    op.drop_table('playlist')
    op.drop_table('item')
    op.drop_table('image')
    # ### end Alembic commands ###
