"""Add playlist and item models

Revision ID: 979da9b7aff0
Revises: a2ced875a244
Create Date: 2021-10-31 13:09:14.064217

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '979da9b7aff0'
down_revision = 'a2ced875a244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_artist'), 'item', ['artist'], unique=False)
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_index(op.f('ix_item_title'), 'item', ['title'], unique=False)
    op.create_table('playlist',
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spotify', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amazon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apple_music', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_amazon'), 'playlist', ['amazon'], unique=False)
    op.create_index(op.f('ix_playlist_apple_music'), 'playlist', ['apple_music'], unique=False)
    op.create_index(op.f('ix_playlist_category_id'), 'playlist', ['category_id'], unique=False)
    op.create_index(op.f('ix_playlist_entity_id'), 'playlist', ['entity_id'], unique=False)
    op.create_index(op.f('ix_playlist_id'), 'playlist', ['id'], unique=False)
    op.create_index(op.f('ix_playlist_image'), 'playlist', ['image'], unique=False)
    op.create_index(op.f('ix_playlist_name'), 'playlist', ['name'], unique=False)
    op.create_index(op.f('ix_playlist_release_date'), 'playlist', ['release_date'], unique=False)
    op.create_index(op.f('ix_playlist_spotify'), 'playlist', ['spotify'], unique=False)
    op.create_table('playlistitemlink',
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'item_id')
    )
    op.create_index(op.f('ix_playlistitemlink_item_id'), 'playlistitemlink', ['item_id'], unique=False)
    op.create_index(op.f('ix_playlistitemlink_playlist_id'), 'playlistitemlink', ['playlist_id'], unique=False)
    op.drop_index('ix_category_playlists', table_name='category')
    op.drop_column('category', 'playlists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('playlists', sa.VARCHAR(), nullable=False))
    op.create_index('ix_category_playlists', 'category', ['playlists'], unique=False)
    op.drop_index(op.f('ix_playlistitemlink_playlist_id'), table_name='playlistitemlink')
    op.drop_index(op.f('ix_playlistitemlink_item_id'), table_name='playlistitemlink')
    op.drop_table('playlistitemlink')
    op.drop_index(op.f('ix_playlist_spotify'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_release_date'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_name'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_image'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_id'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_entity_id'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_category_id'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_apple_music'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_amazon'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_index(op.f('ix_item_title'), table_name='item')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_index(op.f('ix_item_artist'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
